# Generated by Django 5.0.4 on 2024-04-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0002_room_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
    ]
