# Generated by Django 5.0.4 on 2024-04-27 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0003_remove_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='usuarios',
            field=models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
