# Generated by Django 5.0.4 on 2024-05-07 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0004_room_usuarios_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='baneado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_desbaneo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
