# Generated by Django 5.0.4 on 2024-05-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0005_usuario_baneado_usuario_fecha_desbaneo_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_desbaneo',
        ),
    ]
