# Generated by Django 5.0.4 on 2024-06-02 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0006_remove_usuario_fecha_desbaneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='seguidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
