# Generated by Django 5.0.4 on 2024-06-02 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0007_usuario_seguidores'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='seguidos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_seguidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='usuarios_seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
