# Generated by Django 5.0.4 on 2024-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0008_usuario_seguidos_alter_usuario_seguidores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.ImageField(default='insignias/default.png', upload_to='insignias/')),
                ('tipo_reto', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
