# Generated by Django 5.0.4 on 2024-06-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0010_usuarioinsignia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insignia',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='insignia',
            name='tipo_reto',
        ),
    ]
