# Generated by Django 5.0.6 on 2024-06-10 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0011_remove_insignia_condicion_remove_insignia_tipo_reto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioinsignia',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='usuarioinsignia',
            name='fecha_asignacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='insignia_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insignia_en_perfil', to='SkillsHub.usuarioinsignia'),
        ),
        migrations.AlterField(
            model_name='insignia',
            name='icono',
            field=models.ImageField(upload_to='insignias/'),
        ),
    ]
