# Generated by Django 5.0.6 on 2024-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0012_remove_usuarioinsignia_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioinsignia',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
