# Generated by Django 5.0.6 on 2024-06-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0013_usuarioinsignia_activa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioinsignia',
            name='activa',
        ),
    ]
