# Generated by Django 5.0.4 on 2024-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0016_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
