# Generated by Django 5.0.4 on 2024-06-12 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsHub', '0018_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
